const restrictedArtists = [
	'Amaryllis',
	'Archolekas',
	'Black Sabbath',
	'Blake Shelton',
	'Bloody Hawk',
	'Bob Marley & The Wailers',
	'Bob Seger',
	'Christos Cholidis',
	'Clout Music',
	'Crosby Stills & Nash',
	'Dadju',
	'Daphne Lawrence',
	'David Bowie',
	'Def Leppard',
	'Diablo',
	'DJ.Silence',
	'Don Henley',
	'Eagles',
	'Ed Sheeran',
	'Eric Clapton',
	'Etienne Daho',
	'Faber',
	'Flare',
	'Fleetwood Mac',
	'Foals',
	'Frank Sinatra',
	'Genesis',
	'George Harrison',
	'George Mazonakis',
	'Glenn Frey',
	'GODSQUAD',
	'Grateful Dead',
	'Green Day',
	'Harukamirai',
	'Helena Paparizou',
	'Helene Fischer',
	'Herbert Grönemeyer',
	'HKT48',
	'IZ*ONE',
	'Jackson Browne',
	'James Taylor',
	'Jay-Z',
	'John Lennon',
	'K.I.Z',
	'Kenshi Yonezu',
	'Kraftklub',
	'La Clique Music',
	'Led Zeppelin',
	'Lis',
	'Macklemore',
	'Madonna',
	'Maraveyas',
	'Metallica',
	'MG',
	'MILAN',
	'Minami Takahashi',
	'MONSTA X',
	'Morfoula Iakovidou',
	'Mouzourakis',
	'Muse',
	'My Hair Is Bad',
	'Neil Young',
	'NGT48',
	'Nikos Oikonomopoulos',
	'Oge',
	'Panagiotis Chatzipapas',
	'Pantelis Pantelidis',
	'Paul McCartney',
	'Phil Collins',
	'Pink Floyd',
	'Prince',
	'Queen',
	'Rammstein',
	'Red Hot Chili Peppers',
	'Rena Morfi',
	'Rihanna',
	'Roberta Flack',
	'Rod Stewart',
	'Sakis Rouvas',
	'Seiko Matsuda',
	'Sheena Ringo',
	'SHINee',
	'Slimane',
	'Slogan',
	'Snik',
	'Solmeister',
	'Spitz',
	'Steely Dan',
	'Steve Miller',
	'Stevie B',
	'TAEMIN',
	'Tamta',
	'Team H',
	'TETSUYA',
	'The Beatles',
	'The Black Keys',
	'The Doors',
	'Tokyo Incidents',
	'Tom Waits',
	"Top Notch / Noah's Ark",
	'TOQUEL (Klaudio Dhespo)',
	'Tracy Chapman',
	'Van Halen',
	'Van Morrison',
	'WOMCADOLE',
	'Yumi Arai',
	'Yumi Matsutoya',
]

module.exports = restrictedArtists
